# Generated by Django 4.2.7 on 2023-11-03 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodiehotspots', '0002_rate_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(default='0.0', max_length=100),
        ),
    ]
